2021-0518-01)
  3)BLOB
  .이진자료 저장
  .대상이 되는 이진자료는 데이터베이스 '내부'에 저장
  .최대 4GB 저장 가능
  (사용형식)
  컬럼명 BLOB;
  
  
사용예)
CREATE TABLE TEMP09(
  COL1  BLOB);
 **자료저장시 INSERT INTO문으로 사용할 수 없음
   => 익명블록 사용
   
   
DECLARE
  L_DIR VARCHAR2(20):='TEST_DIR';
  L_FILE VARCHAR2(30):='SAMPLE.jpg';
  L_BFILE BFILE;
  L_BLOB BLOB;
BEGIN
  INSERT INTO TEMP09(COL1) VALUES(EMPTY_BLOB())
    RETURN COL1 INTO L_BLOB;
    
  L_BFILE := BFILENAME(L_DIR, L_FILE);
  DBMS_LOB.FILEOPEN(L_BFILE, DBMS_LOB.FILE_READONLY);
  DBMS_LOB.LOADFROMFILE(L_BLOB, L_BFILE, DBMS_LOB.GETLENGTH(L_BFILE));
  DBMS_LOB.FILECLOSE(L_BFILE);
  
  COMMIT;
END;

SELECT * FROM TEMP09;



  